version: '2'

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
  redis:
    image: redis
